type Lead {
  enteredBy: String!
  reviewedBy: String
  name: String!
  description: String!
  phoneNumber: String
  emailAddress: String
  streetAddress: String
  city: String
  state: String
  zipcode: String
  preferedContactMethod: String
  region: String
  mobile: Boolean
  comment: String
  booked: Boolean
  source: String!
  archived: Boolean
}

type Query {
  allLeads: [Lead]!
}
